/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as LedgersRouteImport } from './routes/ledgers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoginHistoryRouteImport } from './routes/login-history'
import { Route as MembersRouteImport } from './routes/members'
import { Route as NotifyRouteImport } from './routes/notify'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as VouchersRouteImport } from './routes/vouchers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgersRoute = LedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginHistoryRoute = LoginHistoryRouteImport.update({
  id: '/login-history',
  path: '/login-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyRoute = NotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/complaints': typeof ComplaintsRoute
  '/emergency': typeof EmergencyRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/login-history': typeof LoginHistoryRoute
  '/members': typeof MembersRoute
  '/notify': typeof NotifyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/visitors': typeof VisitorsRoute
  '/vouchers': typeof VouchersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/complaints': typeof ComplaintsRoute
  '/emergency': typeof EmergencyRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/login-history': typeof LoginHistoryRoute
  '/members': typeof MembersRoute
  '/notify': typeof NotifyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/visitors': typeof VisitorsRoute
  '/vouchers': typeof VouchersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/committee': typeof CommitteeRoute
  '/complaints': typeof ComplaintsRoute
  '/emergency': typeof EmergencyRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/login-history': typeof LoginHistoryRoute
  '/members': typeof MembersRoute
  '/notify': typeof NotifyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/visitors': typeof VisitorsRoute
  '/vouchers': typeof VouchersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/committee'
    | '/complaints'
    | '/emergency'
    | '/ledgers'
    | '/login'
    | '/login-history'
    | '/members'
    | '/notify'
    | '/profile'
    | '/settings'
    | '/staff'
    | '/visitors'
    | '/vouchers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/committee'
    | '/complaints'
    | '/emergency'
    | '/ledgers'
    | '/login'
    | '/login-history'
    | '/members'
    | '/notify'
    | '/profile'
    | '/settings'
    | '/staff'
    | '/visitors'
    | '/vouchers'
  id:
    | '__root__'
    | '/'
    | '/committee'
    | '/complaints'
    | '/emergency'
    | '/ledgers'
    | '/login'
    | '/login-history'
    | '/members'
    | '/notify'
    | '/profile'
    | '/settings'
    | '/staff'
    | '/visitors'
    | '/vouchers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommitteeRoute: typeof CommitteeRoute
  ComplaintsRoute: typeof ComplaintsRoute
  EmergencyRoute: typeof EmergencyRoute
  LedgersRoute: typeof LedgersRoute
  LoginRoute: typeof LoginRoute
  LoginHistoryRoute: typeof LoginHistoryRoute
  MembersRoute: typeof MembersRoute
  NotifyRoute: typeof NotifyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  VisitorsRoute: typeof VisitorsRoute
  VouchersRoute: typeof VouchersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledgers': {
      id: '/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof LedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-history': {
      id: '/login-history'
      path: '/login-history'
      fullPath: '/login-history'
      preLoaderRoute: typeof LoginHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify': {
      id: '/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof NotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommitteeRoute: CommitteeRoute,
  ComplaintsRoute: ComplaintsRoute,
  EmergencyRoute: EmergencyRoute,
  LedgersRoute: LedgersRoute,
  LoginRoute: LoginRoute,
  LoginHistoryRoute: LoginHistoryRoute,
  MembersRoute: MembersRoute,
  NotifyRoute: NotifyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  VisitorsRoute: VisitorsRoute,
  VouchersRoute: VouchersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
